# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7e70b8ab8adf150c34193a9f8a7f99fe1b5288e70d387e80c1c175815b94af3d43afcb9ee873e28f3827f12ab80e3324c266ec1bb2e57076fb321b1b8a41b99

test:
  secret_key_base: 18398f4903622fd154397660c2a7a042cd3847f528ee43def19a67385d11f3936606d6a5618632b4136bf410072c8000b05561fe25ec21219496256c9db16117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
